# Generated by Django 4.2.7 on 2023-11-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='товар'),
        ),
    ]
